# Generated by Django 6.1.1 on 2026-09-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HR', 'HR / Admin'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], default='STUDENT', max_length=20),
        ),
    ]
