# Generated by Django 6.1.1 on 2026-09-10 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20)),
                ('event', models.CharField(choices=[('PROFILE_CREATED', 'Profile Created'), ('PORTFOLIO_SUBMITTED', 'Portfolio Submitted'), ('PORTFOLIO_APPROVED', 'Portfolio Approved'), ('REVISION_REQUIRED', 'Revision Required'), ('PORTFOLIO_REJECTED', 'Portfolio Rejected'), ('PORTFOLIO_PUBLISHED', 'Portfolio Published'), ('GENERIC', 'Generic')], default='GENERIC', max_length=50)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
