# Generated by Django 6.1.1 on 2026-09-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming'), ('TECHNICAL', 'Technical Skills'), ('FRAMEWORK', 'Frameworks'), ('DATABASE', 'Database'), ('CLOUD', 'Cloud'), ('TOOL', 'Tools'), ('SOFT', 'Soft Skills'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveSmallIntegerField(default=3, help_text='1-5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'skills',
                'ordering': ['category', 'name'],
            },
        ),
    ]
