# Generated by Django 6.1.1 on 2026-09-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('HACKATHON', 'Hackathon'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('CLUB', 'Club'), ('VOLUNTEERING', 'Volunteering'), ('COMPETITION', 'Competition'), ('EVENT', 'Event'), ('CO_CURRICULAR', 'Co-curricular'), ('SPORTS', 'Sports / PET'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-date'],
            },
        ),
    ]
