# Generated by Django 6.1.1 on 2026-09-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Achievement')),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('level', models.CharField(choices=[('COLLEGE', 'College'), ('DISTRICT', 'District'), ('STATE', 'State'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], default='COLLEGE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='achievement_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
