# Generated by Django 6.1.1 on 2026-09-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=200, verbose_name='College / School')),
                ('degree', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('year_of_study', models.CharField(blank=True, max_length=20)),
                ('klass', models.CharField(blank=True, max_length=20, verbose_name='Class')),
                ('section', models.CharField(blank=True, max_length=20)),
                ('board', models.CharField(blank=True, max_length=100)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('history', models.TextField(blank=True, help_text='Academic history / remarks')),
                ('start_year', models.CharField(blank=True, max_length=20)),
                ('end_year', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='students.student')),
            ],
            options={
                'ordering': ['-end_year'],
            },
        ),
    ]
